#!/usr/bin/env bash
# Usage: subr commands
# Summary: List all subr commands
# Help: This command is mostly used for autocompletion in various shells, and for `subr help`.
# Also, this command helps find commands that are named the same as potentially builtin shell commands (which, cd, etc)

set -e

path="$_SUBR_ROOT/libexec"
if [ -n $1 ]; then
  path="$path/$1"
fi

find -L $path -maxdepth 1 -mindepth 1 -type f -perm +111 -printf "%f\n"
