#!/usr/bin/env bash
set -e

COMMAND="$1"

command_path="$_SUBR_ROOT/libexec"
while [ -n "$COMMAND" ]; do
  command_path="$command_path/$COMMAND"
  if [ ! -d "$command_path" -a -x "$command_path" ]; then
    break
  fi
  shift
  COMMAND="$1"
done

if [ -d "$command_path" ]; then
  find $command_path -maxdepth 1 -mindepth 1 -executable -printf "%f\n"
else
  if grep -i "^# provide subr completions" "$command_path" >/dev/null; then
    shift
    exec "$command_path" --complete "$@"
  fi
fi
