#!/usr/bin/env bash
set -e

COMMAND="$1"

source "$_SUBR_ROOT/libexec/subr.include"
get_path_from_command "$@"

if [ -d "$command_path" ]; then
  for file in $command_path/*; do
    if [ -x "$file" ]; then
      echo $(basename "$file")
    fi
  done
else
  if grep -i "^# provide subr completions" "$command_path" >/dev/null; then
    shift
    exec "$command_path" --complete "${remaining_args[@]}"
  fi
fi
