#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"

export _SUBR_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

# set sub path if it exists
if [ -n "$_SUBR_SUB_COMMAND" ]; then
  sub_path=$(echo $_SUBR_SUB_COMMAND | tr ' ' '/')
  if [ -d "$libexec_path/$sub_path" ]; then
    export _SUBR_SUB_PATH="$libexec_path/$sub_path"
  else
    echo "ERROR: Could not find $libexec_path/$sub_path" >&2
    exit 1
  fi
fi

source "$_SUBR_ROOT/libexec/subr.include"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec help
  ;;
* )
  get_path_from_command $@
  if [ ! -d "$command_path" -a -x "$command_path" ]; then
    if [ ! -z "$remaining_args" ]; then
      exec "$command_path" "$remaining_args"
    else
      exec "$command_path"
    fi
  else
    echo "subr: no such command \`$@'" >&2
    exit 1
  fi
  ;;
esac
