#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
args=$@
export _SUBR_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec subr-help
  ;;
* )
  command_path="$libexec_path"
  while [ ! -z $1 ]; do
    if [ ! -d "$command_path/$command" -a -x "$command_path/$command" ]; then
      break
    fi
    command_path="$command_path/$command"
    shift
    command="$1"
  done

  if [ -z "$command" ]; then
    echo "subr: no such command \`$args'" >&2
    exit 1
  fi

  shift
  exec "$command_path/$command" "$@"
  ;;
esac
